### ISSUE TITLE
About Deblur-IQA metrics for evaluating RWBI datasets？

### ISSUE THREAD

**Issue by BingY998** [chaeyeongyoon/SimpleNet-pytorch#1]
Hello, thank you very much for your excellent work! When I read this paper, I wanted to test the RWBI dataset, but I couldn't find the code to measure Deblur-IQA, what method did you use to measure Deblur-IQA? Could you tell me some tips or share it? Thank you very much!

**Comment by chaeyeongyun** [comment]
Hi, it's unofficial code implementation. I implemented this paper just for comparative experiment of my paper. So I only measured PSNR and SSIM. I'm sorry that I can't tell you some tips.
